server:
  port: 9041

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
     preferIpAddress: true

spring:
  datasource:
    url: jdbc:mysql://47.95.2.132:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 5
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    com.ibatis: 'DEBUG'
    com.ibatis.common.jdbc.SimpleDataSource: 'DEBUG'
    com.ibatis.common.jdbc.ScriptRunner: 'DEBUG'
    com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: 'DEBUG'
    java.sql.Connection: 'DEBUG'
    java.sql.Statement: 'DEBUG'
    java.sql.PreparedStatement: 'DEBUG'

mybatis:
    mapper-locations: classpath:/cn/aldd/vape/user/micro/repository/mybatis/mapper/*.xml
    logImpl: COMMONS_LOGGING

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
ftp:
    host: 47.95.2.132
    port: 21
    user: ftpadmin
    pwd: qwer1234!   